services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
  api:
    container_name: api
    depends_on:
      - postgres
    env_file: good-works-api/.env
    build:
      context: ./good-works-api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - JWT_SECRET=How much have cost us evils that never happened
  client:
    container_name: client
    depends_on:
      - api
    build:
      context: ./good-works-client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: good-works-api/.env
    ports:
      - 3000:3000
